### ISSUE TITLE
jasmine "spyOn" does not work in Given, When, Then blocks

### ISSUE THREAD

**Issue by rudylattae** [rudylattae/jasmine-species#1]
Allen reported an issue he was having trying to use spies in Feature -> Scenario - >Given, ... setup. See: http://groups.google.com/group/jasmine-js/browse_thread/thread/22cede08b0932872

This issue will act as a progress tracker while I attempt to find a resolution.

**Comment by rudylattae** [comment]
Currently a "scenario" is a suite. "given" and "when" also generate suites. This is a problem in that, spies need to live in a spec. There is also another more subtle problem:
- Conceptually a "scenario" is a single spec. It is not a suite of specs.
- The "given", "when", ... blocks are acually _parts_ of the spec, aka "steps" 

Based on the above, I would say the initial implementation of scenarios and the "given" "when" grammar elements are flawed. Once they are properly implemented, this issue should automatically be resolved.

I'll attempt to re-cast the "scenario" element as a spec and the elements in the GWT module as "runs" blocks.

Wish me luck!

**Comment by rudylattae** [comment]
After a quick check I realized that jasmine "runs" blocks do not have any descriptive text associated. Based on this finding and also the fact that specs within a suite are run in sequence, I'll go ahead and implement the solution as follows:
- All GWT elements: "given", "when",... will generate specs within the current suite - just likt "it"
- The "scenario" element in the FeatureStory module will maintain its current behavior.

**Comment by rudylattae** [comment]
I wrestled with how to implement this fix for a while. After flip-flopping a couple of times I've decided to go with the first idea:
- Conceptually a "scenario" is a single spec. It is not a suite of specs.
- The "given", "when", ... blocks are acually parts of the spec, aka "steps"

**The good**

Now all GWT grammar elements create "runs" blocks in the current spec. Also the "scenario" element from the FeatureStory module now creates a spec instead of a suite.

**The bad**

Jasmine's current implementation of a "runs" block does not allow for a description parameter. As such all the blocks generated by given, when, then... will just run in sequence but will not have a truly useful context when they fail.

**The OK**

Now "given", "when", ... dynamically add a "details" property to to the current spec. The details property is where we stash the description provided with any use of "given", "when", ...

So all I need to do is display that info to provide some context for a scenario.

**TODO:**
1. Convert the "details" element from the More module to "summary"
2. Enhance the StyledHtmlReporter to output details of any spec -- if it exists.

---

You can checkout the current tip of master if you want to take these changes for a spin. Please note that it's still a work in progress and a few more things need to be changed before it becomes production worthy.

**Comment by rudylattae** [comment]
This issue has been resolved in the tip of mater. Closing.

**Comment by abierbaum** [comment]
Thanks for the hard work on this fix.  I am updating my project today to make use of the new capabilities.  They look perfect.

**Comment by rudylattae** [comment]
Good news. Let me know if you have any more issues.

On 2011-04-10 12:17 PM, "abierbaum" <
reply@reply.github.com>
wrote:

Thanks for the hard work on this fix.  I am updating my project today to
make use of the new capabilities.  They look perfect.

## 

Reply to this email directly or view it on GitHub:
https://github.com/rudylattae/jasmine-species/issues/1#comment_980505
